server:
  port: 8088
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}?createDatabaseIfNotExist=${DATABASE_CREATE}&serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect
    show-sql: ${DATABASE_SHOW_SQL}
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect.storage_engine: innodb
  data:
    jpa.repositories.enabled: true
  flyway:
    locations:
      - classpath:/db/migration
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  kafka:
    template:
      default-topic: ${KAFKA_TOPIC_DEFAULT}
    producer:
      bootstrap-servers: ${KAFKA_HOST}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics:
      meetup-participant: ${KAFKA_TOPIC}
cron:
  schedule:
    task:
      example: ${jobs.cronSchedule:0/15 * * * * ?}