server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/db_participants?serverTimezone=UTC
    username: root
    password: admin1
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect.storage_engine: innodb
  data:
    jpa.repositories.enabled: true
  jackson:
    time-zone: America/Argentina/Buenos_Aires
  kafka:
    template:
      default-topic: meetups-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: localhost:9092