server:
  port: 8088
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    properties.hibernate.dialect.storage_engine: innodb
  data:
    jpa.repositories.enabled: true
  h2:
    console:
      enabled: true
  kafka:
    template:
      default-topic: topic-default-test
    topics:
      meetup-participant: topic-test
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      auto-offset-reset: earliest
    embedded:
      kafka:
        broker:
          partitions: 1
          brokerProperties:
            listeners: PLAINTEXT://localhost:9092
            port: 9092
          properties:
            auto.create.topics.enable: true
  flyway:
    locations:
      - classpath:/db/migration-test
      - classpath:/db/migration
logging:
  level:
    org:
      flywaydb:
        core:
          internal:
            resolver:
              sql:
                SqlMigrationExecutor=DEBUG:
cron:
  schedule:
    task:
      example: ${jobs.cronSchedule:0/5 * * * * ?}
